#!/usr/bin/env node
/**
 * Derives this project's whole dark-theme color palette from ONE primary
 * color per named theme (scripts/web-themes.json — a theme's primaryColor,
 * or WEB_PRIMARY_COLOR env var, or the original #1ac3ff, in that order, so
 * an unconfigured deployment with only the "default" theme looks identical
 * to before this existed) and writes each as a plain Sass variables file,
 * consumed by public/scss/custom.scss before Bootstrap's own component
 * partials compile.
 *
 * Uses culori's OKLCH color space (perceptually uniform — equal numeric
 * steps in lightness/hue look evenly spaced to the eye, unlike raw HSL)
 * rather than hand-picking each color independently the way
 * public/css/theme.css used to.
 *
 * The one hard requirement this exists to satisfy: danger/success must
 * stay visually distinct from an arbitrary user-chosen primary — e.g. if
 * primary IS red, danger can't also land on red. This is enforced by
 * measuring the actual circular hue distance between primary and each
 * target zone and shifting the zone's center away from primary when
 * they'd otherwise collide, rather than assuming fixed hue zones never
 * overlap with a user's choice.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
import { oklch, formatHex } from 'culori';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DEFAULT_PRIMARY = '#1ac3ff';
const MIN_HUE_SEPARATION = 40; // degrees; below this, hues read as "the same color family"

export function circularHueDistance(a, b) {
  const diff = Math.abs(a - b) % 360;
  return diff > 180 ? 360 - diff : diff;
}

/**
 * Picks a hue for a semantic color (danger/success), centered on
 * `targetHue`, pushed away from `primaryHue` by at least
 * MIN_HUE_SEPARATION if it would otherwise land too close.
 */
export function resolveHue(targetHue, primaryHue) {
  const distance = circularHueDistance(targetHue, primaryHue);
  if (distance >= MIN_HUE_SEPARATION) {
    return targetHue;
  }
  // Push the target hue away from primary, along whichever direction
  // increases the gap, by just enough to clear the minimum separation.
  const shift = MIN_HUE_SEPARATION - distance;
  const clockwise = (targetHue + shift + 360) % 360;
  const counterClockwise = (targetHue - shift + 360) % 360;
  const clockwiseDistance = circularHueDistance(clockwise, primaryHue);
  const counterClockwiseDistance = circularHueDistance(counterClockwise, primaryHue);
  return clockwiseDistance >= counterClockwiseDistance ? clockwise : counterClockwise;
}

function toHex(l, c, h) {
  return formatHex({ mode: 'oklch', l, c, h: ((h % 360) + 360) % 360 });
}

export function generatePalette(primaryHex) {
  const primary = oklch(primaryHex);
  if (!primary || Number.isNaN(primary.h)) {
    throw new Error(`WEB_PRIMARY_COLOR "${primaryHex}" isn't a color culori can parse as OKLCH (it may be achromatic — pick a color with some saturation).`);
  }
  const primaryHue = primary.h;

  // Grays: primary's own hue at very low chroma, varying only lightness —
  // reproduces today's "blue/green-tinted gray" effect generically for
  // whatever hue the self-hoster's primary happens to be, not just cyan.
  const grayChroma = 0.012;
  const bodyBg = toHex(0.19, grayChroma, primaryHue);
  const tertiaryBg = toHex(0.15, grayChroma, primaryHue);
  const secondaryBg = toHex(0.145, grayChroma, primaryHue);
  const borderColor = toHex(0.28, grayChroma * 1.6, primaryHue);
  const bodyColor = toHex(0.9, grayChroma * 0.6, primaryHue);
  const secondaryColor = toHex(0.68, grayChroma * 1.4, primaryHue);

  // Danger (red/orange zone) and success (green zone), each clamped away
  // from primary's own hue if they'd otherwise collide.
  const dangerHue = resolveHue(25, primaryHue);
  const successHue = resolveHue(155, primaryHue);

  const danger = toHex(0.62, 0.19, dangerHue);
  const success = toHex(0.72, 0.17, successHue);

  const primaryOut = formatHex(primary);

  return {
    primary: primaryOut,
    danger,
    success,
    bodyBg,
    tertiaryBg,
    secondaryBg,
    borderColor,
    bodyColor,
    secondaryColor,
  };
}

function toScss(palette) {
  return `// AUTO-GENERATED by scripts/generate-palette.js — do not hand-edit.
// Regenerated on every \`npm run build:web\` from WEB_PRIMARY_COLOR (see
// .env.example). Deleting this file is safe; the next build recreates it.

$primary: ${palette.primary};
$danger: ${palette.danger};
$success: ${palette.success};

$body-bg-dark: ${palette.bodyBg};
$body-color-dark: ${palette.bodyColor};
$body-secondary-color-dark: ${palette.secondaryColor};
$body-secondary-bg-dark: ${palette.secondaryBg};
$body-tertiary-bg-dark: ${palette.tertiaryBg};
$border-color-dark: ${palette.borderColor};
`;
}

/**
 * Reads scripts/web-themes.json, resolving each theme's primaryColor
 * (null → WEB_PRIMARY_COLOR env var → DEFAULT_PRIMARY, same fallback chain
 * as before this manifest existed — so an unconfigured deployment with only
 * the "default" theme behaves identically to a single-theme build).
 * @returns {Record<string, string>} theme name -> primary color
 */
export function loadThemeManifest() {
  const manifestPath = path.join(__dirname, 'web-themes.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const resolved = {};
  for (const [name, { primaryColor }] of Object.entries(manifest)) {
    resolved[name] = primaryColor || process.env.WEB_PRIMARY_COLOR || DEFAULT_PRIMARY;
  }
  return resolved;
}

export function main() {
  const themes = loadThemeManifest();
  for (const [name, primaryHex] of Object.entries(themes)) {
    const palette = generatePalette(primaryHex);
    const outPath = path.join(__dirname, `../public/scss/_generated-palette-${name}.scss`);
    fs.writeFileSync(outPath, toScss(palette));
    console.log(`✓ Generated ${path.relative(process.cwd(), outPath)} (theme "${name}") from primary ${primaryHex}`);
    console.log(`  primary=${palette.primary} danger=${palette.danger} success=${palette.success}`);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
